export let lettersData = [
  { id: 1, type: 2, typeName: '中子音', text: 'ก', start: 0, dur: 2000, sound: 'gor gài', vocabulary: 'ก.ไก่', mean: '雞' },
  { id: 2, type: 3, typeName: '高子音', text: 'ข', start: 1, dur: 2000, sound: 'kor kài', vocabulary: 'ข.ไข่', mean: '蛋' },
  { id: 3, type: 3, typeName: '高子音', text: 'ฃ', start: 3, dur: 2500, sound: 'kor kûuat', vocabulary: 'ฃ.ขวด', mean: '瓶罐' },
  { id: 4, type: 1, typeName: '低子音', text: 'ค', start: 5, dur: 2000, sound: 'kor kwaai', vocabulary: 'ค.ควาย', mean: '水牛' },
  { id: 5, type: 1, typeName: '低子音', text: 'ฅ', start: 7, dur: 2300, sound: 'kor kon', vocabulary: 'ฅ.คน', mean: '人' },
  { id: 6, type: 1, typeName: '低子音', text: 'ฆ', start: 9, dur: 2000, sound: 'kor rá-kang', vocabulary: 'ฆ.ระฆัง', mean: '大鐘' },
  { id: 7, type: 1, typeName: '低子音', text: 'ง', start: 10, dur: 2000, sound: 'ngor ngoo', vocabulary: 'ง.งู', mean: '蛇' },
  { id: 8, type: 2, typeName: '中子音', text: 'จ', start: 12, dur: 2000, sound: 'jor jaan', vocabulary: 'จ.จาน', mean: '盤子' },
  { id: 9, type: 3, typeName: '高子音', text: 'ฉ', start: 14, dur: 2000, sound: 'chor chìng', vocabulary: 'ฉ.ฉิ่ง', mean: '小拔' },
  { id: 10, type: 1, typeName: '低子音', text: 'ช', start: 16, dur: 2000, sound: 'chor cháang', vocabulary: 'ช.ช้าง', mean: '大象' },
  { id: 11, type: 1, typeName: '低子音', text: 'ซ', start: 18, dur: 2000, sound: 'sor sôh', vocabulary: 'ซ.โซ่', mean: '鎖鏈' },
  { id: 12, type: 1, typeName: '低子音', text: 'ฌ', start: 20, dur: 2000, sound: 'chor cher', vocabulary: 'ฌ.เฌอ', mean: '樹木' },
  { id: 13, type: 1, typeName: '低子音', text: 'ญ', start: 22, dur: 2300, sound: 'yor yĭng', vocabulary: 'ญ.หญิง', mean: '女' },
  { id: 14, type: 1, typeName: '', text: 'ฎ', start: 24, dur: 2200, sound: 'dor cha da', vocabulary: 'ฎ.ชฎา', mean: '尖頂冠' },
  { id: 15, type: 2, typeName: '中子音', text: 'ฏ', start: 26, dur: 2000, sound: 'dtor bpà-dtàk', vocabulary: 'ฏ.ปฏัก', mean: '茅武器' },
  { id: 16, type: 3, typeName: '高子音', text: 'ฐ', start: 28, dur: 2000, sound: 'tor tăan', vocabulary: 'ฐ.ฐาน', mean: '塔' },
  { id: 17, type: 1, typeName: '低子音', text: 'ฑ', start: 30, dur: 2000, sound: 'tor mon-toh', vocabulary: 'ฑ.มณโฑ', mean: '魔后' },
  { id: 18, type: 1, typeName: '低子音', text: 'ฒ', start: 31, dur: 2000, sound: 'tor pôo tâo', vocabulary: 'ฒ.ผู้เฒ่า', mean: '老人' },
  { id: 19, type: 1, typeName: '低子音', text: 'ณ', start: 34, dur: 1800, sound: 'nor nen', vocabulary: 'ณ.เณร', mean: '沙彌' },
  { id: 20, type: 2, typeName: '中子音', text: 'ด', start: 35.5, dur: 2000, sound: 'dor dèk', vocabulary: 'ด.เด็ก', mean: '小朋友' },

  { id: 21, type: 2, typeName: '中子音', text: 'ต', start: 37, dur: 2000, sound: 'dtor dtào', vocabulary: 'ต.เต่า', mean: '烏龜' },
  { id: 22, type: 3, typeName: '高子音', text: 'ถ', start: 38.5, dur: 3000, sound: 'tor tŭng', vocabulary: 'ถ.ถุง', mean: '袋子' },
  { id: 23, type: 1, typeName: '低子音', text: 'ท', start: 41, dur: 2000, sound: 'tor tá-hăan', vocabulary: 'ท.ทหาร', mean: '軍人' },
  { id: 24, type: 1, typeName: '低子音', text: 'ธ', start: 44, dur: 2000, sound: 'tor tong', vocabulary: 'ธ.ธง', mean: '旗子' },
  { id: 25, type: 1, typeName: '低子音', text: 'น', start: 45, dur: 3000, sound: 'nor nŏo', vocabulary: 'น.หนู', mean: '老鼠' },
  { id: 26, type: 2, typeName: '中子音', text: 'บ', start: 47, dur: 3000, sound: 'bor bai mái', vocabulary: 'บ.ใบไม้', mean: '樹葉' },
  { id: 27, type: 2, typeName: '中子音', text: 'ป', start: 50, dur: 2000, sound: 'bpor bplaa', vocabulary: 'ป.ปลา', mean: '魚' },
  { id: 28, type: 3, typeName: '高子音', text: 'ผ', start: 52, dur: 2000, sound: 'por pêung', vocabulary: 'ผ.ผึ้ง', mean: '蜜蜂' },
  { id: 29, type: 3, typeName: '高子音', text: 'ฝ', start: 53, dur: 2500, sound: 'for făa', vocabulary: 'ฝ.ฝา', mean: '蓋子' },
  { id: 30, type: 1, typeName: '低子音', text: 'พ', start: 56, dur: 2000, sound: 'por paan', vocabulary: 'พ.พาน', mean: '奉獻盤' },
  { id: 31, type: 1, typeName: '低子音', text: 'ฟ', start: 58, dur: 2300, sound: 'for fan', vocabulary: 'ฟ.ฟัน', mean: '牙齒' },
  { id: 32, type: 1, typeName: '低子音', text: 'ภ', start: 60, dur: 2500, sound: 'por săm-pao', vocabulary: 'ภ.สำเภา', mean: '三寶船' },
  { id: 33, type: 1, typeName: '低子音', text: 'ม', start: 62, dur: 2000, sound: 'mor máa', vocabulary: 'ม.ม้า', mean: '馬' },
  { id: 34, type: 1, typeName: '低子音', text: 'ย', start: 64, dur: 2000, sound: 'yor yák', vocabulary: 'ย.ยักษ์ ', mean: '巨人' },
  { id: 35, type: 1, typeName: '低子音', text: 'ร', start: 66, dur: 2000, sound: 'ror reuua', vocabulary: 'ร.เรือ', mean: '船' },
  { id: 36, type: 1, typeName: '低子音', text: 'ล', start: 68, dur: 2200, sound: 'lor ling', vocabulary: 'ล.ลิง', mean: '猴子' },
  { id: 37, type: 1, typeName: '低子音', text: 'ว', start: 70, dur: 2000, sound: 'wor wăen', vocabulary: 'ว.แหวน', mean: '戒指' },
  { id: 38, type: 3, typeName: '高子音', text: 'ศ', start: 72, dur: 2500, sound: 'sor săa-laa', vocabulary: 'ศ.ศาลา', mean: '涼亭' },
  { id: 39, type: 3, typeName: '高子音', text: 'ษ', start: 74.5, dur: 2000, sound: 'sor réu-sĕe', vocabulary: 'ษ.ฤๅษี', mean: '隱士' },
  { id: 40, type: 3, typeName: '高子音', text: 'ส', start: 76, dur: 2500, sound: 'sor sĕuua', vocabulary: 'ส.เสือ', mean: '虎' },
  { id: 41, type: 3, typeName: '高子音', text: 'ห', start: 79, dur: 2000, sound: 'hor hèep', vocabulary: 'ห.หีบ', mean: '木製箱' },
  { id: 42, type: 1, typeName: '低子音', text: 'ฬ', start: 81, dur: 2200, sound: 'lor jù-laa', vocabulary: 'ฬ.จุฬา', mean: '風箏' },
  { id: 43, type: 2, typeName: '中子音', text: 'อ', start: 83, dur: 2000, sound: 'or àang', vocabulary: 'อ.อ่าง', mean: '甕' },
  {
    id: 44,
    type: 1, typeName: '低子音', text: 'ฮ', start: 85, dur: 2500, sound: 'hor nók hôok', vocabulary: 'ฮ.นกฮูก', mean: '貓頭鷹'
  }
]